### ISSUE TITLE
Create function for change metadata

### ISSUE THREAD

**Issue by MaxLisyanskiy** [MaxLisyanskiy/strada-pet#49]
- [x] Создать функцию, которая принимает необходимые параметры и на основе этих данных генерирует и изменяет уникальные метаданные title и description в теге <head>

<img width="421" alt="image" src="https://github.com/MaxLisyanskiy/strada-pet/assets/59924323/b2425c8d-0315-4d22-9ae2-aee7c6a3b209">

**Comment by AipovAlexander** [comment]
utils - create-meta.ts

**Comment by AipovAlexander** [comment]
Title: Home | News Api 
Title : Profile | News Api
погуглить description, что туда вставлять
